###
GET http://localhost:5000/product

###
GET http://localhost:5000/product/1

###
POST http://localhost:5000/product
Content-Type: application/json

{
    "name": "Product 6",
    "price": 679
}

###
PATCH  http://localhost:5000/product/1
Content-Type: application/json

{
    "name": "Product 1",
    "price": 200
}

###
DELETE http://localhost:5000/product/3